### ISSUE TITLE
I broke the game :c

### ISSUE THREAD

**Issue by AragonCodes** [Ta7ar/O-Tic-Tac-Toe#1]
I was trying the app with two separate 'incognito' windows in Firefox v77.0.1, and I broke the game.

Steps to reproduce:
> Create session with playerOneName
> Join session with code and playerTwoName
> Played playerOneName move
> Got error screen:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/49354167/85206236-f370e480-b2dd-11ea-8f9e-8e7cd00d2686.png">

 Let me know if I can help :]

**Comment by Ta7ar** [comment]
![Screenshot (38)](https://user-images.githubusercontent.com/56931453/85212765-12926500-b324-11ea-9d7b-1778f32db96b.png)

I am sorry but I could not reproduce the crash, works fine for me so I cannot pinpoint a specific issue. Are you perhaps using a VPN or proxies?

**Comment by AragonCodes** [comment]
Maybe it was a problem with the server 🤷‍♂️
